
## if TEST then

	##[[ 

	local cols = require('nelua.utils.console').colors

	local passert_dummy_concept = concept(function(x)
		local t = types.NiltypeType('niltype')
		t.is_equal = function() return false end
		t.text = cols.red .. "x=== FAIL ===x" .. cols.reset
		return t
	end)

	]]

	global function passert(cond: boolean, dummy: #[passert_dummy_concept]#) <polymorphic, inline>
		if not cond then
			error(#[dummy.type.text]#)
		end
	end

## end